  CREATE TABLE "AGENCIA_CIERRES" 
   (	"ID_CIERRE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_AGENCIA" NUMBER NOT NULL ENABLE, 
	"FECHA_CIERRE" DATE NOT NULL ENABLE, 
	"VENTAS" NUMBER DEFAULT 0, 
	"COMPRAS" NUMBER DEFAULT 0, 
	"GASTOS" NUMBER DEFAULT 0, 
	"ACTIVOS" NUMBER DEFAULT 0, 
	"AJUSTES" NUMBER DEFAULT 0, 
	"SALDO" NUMBER, 
	"OBSERVACIONES" VARCHAR2(4000), 
	 PRIMARY KEY ("ID_CIERRE")
  USING INDEX  ENABLE
   ) ;