-- Primero eliminamos las tablas que dependen de otras

DROP TABLE AGENCIA_VENTAS CASCADE CONSTRAINTS;
DROP TABLE AGENCIA_COMPRAS CASCADE CONSTRAINTS;
DROP TABLE AGENCIA_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE AGENCIA_USUARIO CASCADE CONSTRAINTS;

-- Luego las tablas independientes o padres

DROP TABLE TASA_CAMBIO_USD_VES CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE AGENCIA CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;